version: "2"
services:
  my-mvc-app:
    # Depends on docker/compose issue #4790
    # build:
    #   dockerfile: MyMvcApp.Dockerfile
    #   target: develop
    image: my-mvc-app:develop
    ports:
    - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    command: dotnet watch run
  my-mvc-app-tests:
    build:
      dockerfile: MyMvcApp.Tests.Dockerfile
      context: .
    image: my-mvc-app:tests
    command: dotnet watch test
  my-other-app:
    # Depends on docker/compose issue #4790
    # build:
    #   dockerfile: MyOtherApp.Dockerfile
    #   target: develop
    image: my-other-app:develop
    ports:
    - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    command: dotnet watch run
